### ISSUE TITLE
update for gedit 3.18

### ISSUE THREAD

**Issue by futwick** [eguaio/gedit-macropy#6]
I realise this project has not been updated for a few years but...

gedit's interface has changed quite a lot recently and macropy's buttons are no longer being displayed. This means the plugin cannot be used. Can it be modified for the new gedit UI (or have menu items added to start/stop macro recording)?

**Comment by eguaio** [comment]
Hi. Nice to know there is still interest in the plugin. The plugin had the buttons and also menu items (both). Have you tried and check the lack of both features? Please, let me know and I'll see what I can do.

**Comment by futwick** [comment]
Thanks for replying so quickly.

I cannot see menu items or the buttons.

**Comment by eguaio** [comment]
Ok, let me see what I can do.

**Comment by eguaio** [comment]
Would you please run gedit from console to see the errors that are reported?  Thank you!

**Comment by futwick** [comment]
Thanks, here's what I see in the console:
```
Traceback (most recent call last):
  File "/home/futwick/.local/share/gedit/plugins/macropy.py", line 82, in do_activate
    self._add_ui()   
  File "/home/futwick/.local/share/gedit/plugins/macropy.py", line 60, in _add_ui
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
```

**Comment by ricardogith** [comment]
Sure there is still interest in this plugin! Using 3.18.3 I get the same error in terminal as futwick. Any chance it can work in gedit 3.18? I do not have any knowledge of python but is there anything I can do to help?

**Comment by eguaio** [comment]
hello ricardogith, futwick,
I'm sorry I didn't answer about this issue before. The thing is I have an older version installed (3.10.4) and I'm not able to test the problem. I will try to update the version to be able to work on this.

By the way, I wrote this plugin a few years ago. At that time, I was using a lot the C++ version for gedit 2, and when I upgrade it to gedit 3, the plugin stopped working. Since I know python I thought, "what the heck, I'll implement it myself". But I'm not using gedit to much anymore, and this is the reason of the delays in answering. 

Anyway, I like to give back to the community at list a tiny fraction of all I got, so I'll try to continue with the maintenance of the plugin.

**Comment by ricardogith** [comment]
that is really appreciated! just for curiosity...what editor are you using? and does it have a similar functionality that what macropy provides?

**Comment by eguaio** [comment]
I use sublime text now. It is not open-source but well... at least the free version has all the features, you only need to see a pop up "buy me" window every time in a while. The licence is rather cheap if you live in USA (70 dollars), but not for me, in my beloved development country (Argentina) you can buy about 15 pounds of the best meat with that money. And yes indeed, it has all you need from a text editor. It's like the old notepad++ for  windows, but better, and running in all platforms. 
Sorry I couldn't work on this issue, but Leif Martensson upgraded the plugin for gedit 3.18. So, thanks to him, we can close this issue now. Please, come back to report if you find any other issue.

**Comment by eguaio** [comment]
Leif Martensson upgraded the plugin for gedit 3.18.

**Comment by futwick** [comment]
That's great news.

Thank you for the time you put into this plug-in over the years - and thanks to Leif for upgrading it.

**Comment by ricmora** [comment]
Great! Thanks Leif for bringing macropy back to life again!
